<a href="https://colab.research.google.com/github/Arham-Begani/Learning_Pytorch/blob/main/00_pytorch_fundamentas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Fundamentals


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


##**Intro To Tensors**

###          Creating tensors

Pytorch tensors are created using "torch.tensor()"

Scalar

In [19]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

Vector

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
scalar.ndim

0

In [7]:
vector.ndim

1

# Random Tensors


In [20]:
random_tensor = torch.rand(3,6,5)
random_tensor, random_tensor.ndim

(tensor([[[0.3118, 0.5881, 0.2195, 0.2206, 0.3269],
          [0.0341, 0.0599, 0.7935, 0.3453, 0.5298],
          [0.3737, 0.4422, 0.7323, 0.4750, 0.9546],
          [0.0537, 0.3633, 0.2921, 0.9560, 0.2712],
          [0.2367, 0.9964, 0.1144, 0.6222, 0.8929],
          [0.2947, 0.7996, 0.3861, 0.8102, 0.3713]],
 
         [[0.6573, 0.2343, 0.5828, 0.6970, 0.1197],
          [0.5347, 0.7232, 0.8778, 0.5597, 0.0186],
          [0.3494, 0.6234, 0.3233, 0.0311, 0.9349],
          [0.5638, 0.1570, 0.9158, 0.2133, 0.8984],
          [0.9570, 0.5314, 0.4788, 0.9363, 0.4386],
          [0.1047, 0.2523, 0.6350, 0.8365, 0.6778]],
 
         [[0.6746, 0.3759, 0.6549, 0.0490, 0.5801],
          [0.4568, 0.4656, 0.4423, 0.4333, 0.6602],
          [0.5197, 0.7194, 0.2245, 0.4736, 0.6456],
          [0.2715, 0.6779, 0.1821, 0.5547, 0.6215],
          [0.5523, 0.8455, 0.2076, 0.2271, 0.9585],
          [0.5979, 0.4602, 0.8274, 0.5655, 0.1510]]]),
 3)

In [16]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [17]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16



```
# This is formatted as code
```

#Tensor Datatypes

**Note**: Tensor datatypes is one of the big 3 errors with pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [24]:
float16_torch = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                           requires_grad=False) # torch.half would also work

float16_torch.dtype

torch.float16

In [23]:
float32_torch = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=None,
                           requires_grad=False) # torch.half would also work

float32_torch.dtype

torch.float32

In [25]:
float32_torch*float16_torch

tensor([ 9., 36., 81.])

# Gettig info from Tensors

1. Tensors not right datatype - to get a datatype from a tensor we can use 'tensor.dtype'
2. Tensors not right shape - to get the shape from tensor we can use 'tensor.shape'
3. Tensors not on right device - to get device from a tensor we can use 'tensor.device'

